import { ActiveOptions } from "./ActiveOptions";
import { AverageReviews } from "./AverageReviews";
import { DistributedRatings } from "./DistributedRatings";
import { Features } from "./Features";
import { InsurancePlan } from "./InsurancePlan";
import { InsuranceState } from "./InsuranceState";
import { ListingQuestion } from "./ListingQuestion";
import { Locale } from "./Locale";
import { Location } from "./Location";
import { PreferredPrimaryImageClass } from "./PreferredPrimaryImageClass";
import { PrepFee } from "./PrepFee";
import { Ranking } from "./Ranking";
import { SEOContent } from "./SEOContent";
import { TaxRate } from "./TaxRate";


export interface DatumAttributes {
    Explanation: null;
    active_options: ActiveOptions;
    availability_set: boolean;
    average_ratings: { [key: string]: number; };
    average_reviews: AverageReviews | null;
    cancel_policy: string;
    cancel_policy_combo_bookings: string;
    cancel_text: string;
    catalog: null;
    children_count: number;
    coachnet_ready: boolean;
    coachnet_required: boolean;
    combined_special_hours: any[];
    created: Date;
    current_location_id: number;
    custom_insurance_text: string;
    dealer: boolean;
    delivery: boolean;
    delivery_radius: number;
    delivery_usage_item_id: number;
    deposit_percentage: number;
    description: string;
    description_included: string;
    description_other: string;
    description_recommendations: string;
    display_vehicle_type: string;
    distributed_ratings: DistributedRatings;
    education: any[];
    external: boolean;
    favorite: boolean;
    favorite_count: number;
    features: Features;
    first_published: Date;
    generator_usage_item_id: number;
    group_on_map: boolean;
    group_reviews_num: number;
    group_reviews_score: number;
    group_score: number;
    has_been_published: boolean;
    has_checkout_questions: boolean;
    hidden: boolean;
    house_rules: string;
    instant_book: boolean;
    instant_book_leeway: number;
    insurance_coverage: string;
    insurance_eligible: boolean;
    insurance_plan: InsurancePlan;
    insurance_renter_adjustable: boolean;
    insurance_state: InsuranceState;
    last_published: Date;
    listing_questions: ListingQuestion[];
    locale: Locale;
    location: Location;
    mileage_usage_item_id: number;
    minimum_days: number;
    minimum_deposit: number;
    name: string;
    nearby_content: any[];
    original_url: string;
    owner_score: number;
    parent_id: number;
    position: number;
    preferred_primary_image: PreferredPrimaryImageClass;
    prep_fee: PrepFee | null;
    presentment_currency: string;
    price_per_day: number;
    price_per_month: number;
    price_per_week: number;
    primary_image_url: string;
    pro: boolean;
    published: boolean;
    ranking: Ranking;
    rental_score: number;
    request_less_than_minimum_days: number;
    reviews_num: number;
    score: number;
    seatbelts: number;
    security_deposit: number;
    seo_content: SEOContent;
    settlement_currency: string;
    sleeps: number;
    sleeps_adults: number;
    sleeps_kids: number;
    slug: string;
    smart_photo_score: number;
    sort_score: number;
    summary: string;
    tags: any[];
    tax_rates: TaxRate[];
    type: string;
    unavailable: boolean;
    updated: Date;
    use_day_pricing: boolean;
    use_tax_inclusive_pricing: boolean;
    user_slug: string;
    vehicle_amps: number;
    vehicle_box_length: number;
    vehicle_class: string;
    vehicle_dry_weight: number;
    vehicle_gvwr: number;
    vehicle_height: number;
    vehicle_length: number;
    vehicle_length_with_hitch: number;
    vehicle_license_plate_state: string;
    vehicle_make: string;
    vehicle_model: string;
    vehicle_width: number;
    vehicle_year: number;
}
