
export interface Features {
    air_conditioner: boolean;
    audio_inputs: boolean;
    awning: boolean;
    backup_camera: boolean;
    base_weight: number;
    beds_bunk: number | null;
    beds_dinette_conversion: number | null;
    beds_fold_out_sofa: number | null;
    beds_full: number;
    beds_king: number | null;
    beds_other: null;
    beds_queen: number;
    beds_twin: number;
    bike_rack: boolean;
    brake_controller: boolean;
    burning_man_friendly: boolean;
    carrying_capacity: number;
    cd_player: boolean;
    ceiling_fan: boolean;
    connector_type: null | string;
    dining_table: boolean;
    extra_storage: boolean;
    festival_friendly: boolean;
    generator: boolean;
    gray_tank: number;
    gross_vehicle_weight: number;
    handicap_accessible: boolean;
    heater: boolean;
    hitch_weight: number | null;
    hookup_electric: boolean;
    hookup_sewer: boolean;
    hookup_water: boolean;
    hot_water_tank: boolean;
    inside_shower: boolean;
    international_travel_allowed: boolean;
    inverter: boolean;
    kitchen_sink: boolean;
    leveling_jacks: boolean;
    microwave: boolean;
    minimum_age: number | null;
    mpg: number | null;
    one_way_rentals: boolean;
    outside_shower: boolean;
    oven: boolean;
    pet_friendly: boolean;
    propane_tank: number;
    provides_receivers: boolean;
    radio: boolean;
    refrigerator: boolean;
    satellite: boolean;
    sewage_tank: number;
    skylight: boolean;
    slide_outs: number;
    smoking_allowed: boolean;
    solar: boolean;
    stove: boolean;
    tailgate_friendly: boolean;
    toilet: boolean;
    tow_hitch: boolean;
    trailer_weight: number | null;
    tv_dvd: boolean;
    washer_dryer: boolean;
    water_tank: number;
    wifi: boolean;
    fuel_tank?: number;
    fuel_type?: string;
    transmission?: string;
}
